#!/bin/bash
#
#Author : pavan
#date   : 21-10-2024
#Script : Git hub Practice
#
######################
#

echo "Name"
read NAME

echo "age"
read AGE

echo "Qualification"
read QUALIFICATION

echo "My Name is $NAME and $AGE and $QUALIFICATION"

